carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'update/', cart_update, name='update'),
    url(r'checkout/', checkout_home, name='checkout')
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^login/', login_page, name='login'),
    url(r'^register/guest', guest_register_view, name='guest_register'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed
from ecommerce.utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)

        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            print("Cart with id={} already exists".format(cart_id))
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    products =  models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):

    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.095)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect

from .models import Cart
from orders.models import Order
from products.models import Product
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from accounts.models import GuestEmail

def cart_create(user=None):
    cart_obj = Cart.objects.create(user=None)
    return cart_obj

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", context={"cart": cart_obj})

def cart_update(request):

    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            prod_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user that product does not exist")
            return redirect("cart:home")
        prod_obj = Product.objects.get(id=product_id)
        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if prod_obj in cart_obj.products.all():
            cart_obj.products.remove(prod_obj)
        else:
            cart_obj.products.add(prod_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")




def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    user = request.user
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()
    guest_email_id = request.session.get('guest_email_id')
    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)

    elif guest_email_id is not None:
        guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
        billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(email=guest_email_obj.email)
    else:
        pass

    if billing_profile is not None:
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)


    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form
    }

    return render(request, "carts/checkout.html", context=context)

carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}

{{ object.order_id }} -- {{ object.cart }}

{% if not billing_profile %}
<div class="row text-center">
    <div class="col-12 col-md-6">
        <p class="lead">Please login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class="col-12 col-md-6">
        <p class="lead">
            Continue as guest
            {% url 'guest_register' as guest_register_url %}
            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </p>
    </div>
</div>

{% else %}




    <h1>Checkout</h1>
    <p>Cart total: {{ object.cart.total }}</p>
    <p>Shipping total: {{ object.shipping_total }}</p>
    <p>Shipping total: {{ object.total }}</p>

{% endif %}

{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Hello Cart</h1>

{% if cart.products.exists %}
<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Product Name</th>
            <th>Product Price</th>
        </tr>
    </thead>
    <tbody>
        {% for product in cart.products.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
            </td>
            <td>{{ product.price }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2"></td>
            <td><strong>Subtotal: </strong>{{ cart.subtotal }}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td><strong>Total: </strong>{{ cart.total }}</td>
        </tr>
         <tr>
            <td colspan="2"></td>
            <td><a class="btn btn-block btn-success" href="{% url 'cart:checkout' %}">Checkout</a> </td>
        </tr>
    </tbody>
</table>
{% else %}
<p class="lead">Cart is empty</p>

{% endif %}
{% endblock %}